language: python
python:
    - "2.6"
    - "2.7"
    # - "3.2"
    # - "3.3"
install:
    - "python setup.py develop"
    - "pip install pyramid_fullauth[tests] coveralls --use-mirrors"
script:
    - "py.test --cov pyramid_fullauth tests/"
after_success:
    - coveralls

deploy:
    provider: pypi
    user: fizyk
    password:
        secure: Q6P2MZMJdd+BY8Hlh0AJAq1S5y5EKGWcsxb5CbhVoWeo0UiJ/uIqju6AkCijifm4v0wyZ1hjErV8ENMSiVZ4l9dmZDKDgk9MMxfNzCIVYvM1BIBMa1aQtvqOBcIwQ/wV1Dt4h+XftlJaI3p31IEOqScU/Kb/oqCkI/Gs096P+JU=
    on:
        tags: true
        repo: fizyk/pyramid_fullauth
    distributions: "sdist bdist bdist_wheel"

