language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
install:
    - "python setup.py install"
    - "pip install pyramid_fullauth[tests] coveralls --use-mirrors"
script:
    - "python setup.py nosetests"
after_success:
    - coveralls
