language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
env:
    - PYRAMID_VER="==1.5" SQLALCHEMY_VER="==0.8.6"
    - PYRAMID_VER="==1.5" SQLALCHEMY_VER="==0.9.4"
install:
    # install requests first, since setuptools have problem with it.
    - "pip install requests --use-mirrors"
    - "python setup.py develop"
    - "pip install pyramid_fullauth[tests] coveralls pylama pyramid$PYRAMID_VER sqlalchemy$SQLALCHEMY_VER --use-mirrors"
    # manually install wheel for deployment
    - "pip install wheel --use-mirrors"
script:
    - "py.test -v --cov pyramid_fullauth tests/"
    - "pylama"
after_success:
    - coveralls

deploy:
    provider: pypi
    user: fizyk
    password:
        secure: Q6P2MZMJdd+BY8Hlh0AJAq1S5y5EKGWcsxb5CbhVoWeo0UiJ/uIqju6AkCijifm4v0wyZ1hjErV8ENMSiVZ4l9dmZDKDgk9MMxfNzCIVYvM1BIBMa1aQtvqOBcIwQ/wV1Dt4h+XftlJaI3p31IEOqScU/Kb/oqCkI/Gs096P+JU=
    on:
        tags: true
        repo: fizyk/pyramid_fullauth
    distributions: "sdist bdist_egg bdist_wheel"

