name: Test build package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

permissions: {}

jobs:
  build:
    permissions:
      contents: read
    uses: fizyk/actions-reuse/.github/workflows/shared-pypi.yml@bd825c06829614c809e87acac868a1143328a5b4 # v5.3.2
    with:
      dependency-manager: uv
