name: Test build package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

permissions: {}

jobs:
  build:
    permissions:
      contents: read
    uses: fizyk/actions-reuse/.github/workflows/shared-pypi.yml@3768ca868776ab12e78334cc376094a7aec3d9b6 # v5.3.1
    with:
      dependency-manager: uv
