name: PostgreSQL tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    uses: fizyk/actions-reuse/.github/workflows/tests-pytests.yml@v1.6.4
    with:
      python-versions: '["3.8", "3.9", "3.10"]'
      pipenv: true
      pipenv-install-options: "--skip-lock"
      pytest_opts: "-k postgresql"
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
