name: Run pre-commit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    uses: fizyk/actions-reuse/.github/workflows/shared-pre-commit.yml@3768ca868776ab12e78334cc376094a7aec3d9b6 # v5.3.1
