name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to be added'
        required: true
        type: string

permissions: {}

concurrency:
  group: release-schedule

jobs:
  release:
    permissions:
      contents: read
    uses: fizyk/actions-reuse/.github/workflows/shared-release.yml@42b61e053c1d70a61deb42b323c1a2229e2e7fe0 # v5.5.0
    with:
      version: ${{ inputs.version }}
      dependency-manager: 'uv'
    secrets:
      app_id: ${{ secrets.RELEASE_APP_ID }}
      private_key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
