name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, "3.10"]
    env:
      OS: ubuntu-latest
      PYTHON: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
    - name: Run test
      run: |
        py.test -v --cov pyramid_fullauth tests/ --cov-report=xml -k "not mysql and not postgresql"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.0
      with:
        file: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        fail_ci_if_error: true
