name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    uses: fizyk/actions-reuse/.github/workflows/tests-pytests.yml@v2.4.7
    with:
      python-versions: '["3.8", "3.9", "3.10", "3.11", "3.12"]'
      pytest_opts: '-k "not mysql and not postgresql"'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  postgresql:
    needs: tests
    uses: fizyk/actions-reuse/.github/workflows/tests-pytests.yml@v2.4.7
    with:
      python-versions: '["3.8", "3.9", "3.10", "3.11", "3.12"]'
      pytest_opts: "-k postgresql"
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  mysql:
    needs: tests
    uses: fizyk/actions-reuse/.github/workflows/tests-pytests.yml@v2.4.7
    with:
      python-versions: '["3.8", "3.9", "3.10", "3.11", "3.12"]'
      pytest_opts: "-k mysql"
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
